name: Run unit tests

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install dependencies
      run: sudo apt-get install -y build-essential libglib2.0-dev libxml2-dev libcunit1-dev libjansson-dev liblua5.2-dev flake8 python3-pytest python3-ncclient python3-lxml
    - uses: actions/cache@v2
          id: cache-setup
          with:
            path: .build/
            key: ${{ runner.os }}-setup-${{ hashFiles('./run.sh') }}
            restore-keys: |
              ${{ runner.os }}-setup-
        - run: ./run.sh setup
          if: steps.cache-setup.outputs.cache-hit != 'true'
    - name: Run tests
      run: ./run.sh test
